services:
  backend:
    build: .
    container_name: segarkosan-backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: segarkosan-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped
